config/routes.rb
Rails.application.routes.draw do
  root 'pages#feed'
  devise_for :users
  resources :tweets, except: [:show]
  get '/:user_id/tweets/:tweet_id', to: 'tweets#show', as: 'user_tweet'
  get '/:user_id/tweets', to: 'users#show', as: 'user_tweets'

  get '/search_user', to: 'users#search_user'
  get '/search', to: 'users#search'

  post '/follow/:id', to: 'follows#create', as: 'follow'
  delete '/follow/:id', to: 'follows#destroy', as: 'delete_follow'

  get '/:user_id/followers', to: 'follows#follower_users', as: 'follower_users'
  get '/:user_id/followings', to: 'follows#following_users', as: 'followings_users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'user_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, length: {minimum: 1, maximum: 280}

  self.per_page = 10
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged

  self.per_page = 10

  has_many :tweets
  
  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  validates :username, :email, :full_name, presence: true
  validates :email, :username, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def already_followed?(user_id)
    self.following.where("following_id = ?", user_id).exists?
  end

  def self.search(username)
    username.downcase!
    username.strip!
    where("username like ?", "#{username}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :full_name])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    user = User.friendly.find(params[:id])
    follow = Follow.new(user_id: current_user.id, following_id: user.id)
    follow.save
    redirect_to root_path
  end

  def destroy
    user = User.friendly.find(params[:id])
    follow = Follow.where(following_id: user.id, user_id: current_user.id).first
    follow.destroy
    redirect_to root_path
  end

  def follower_users
    @user = User.friendly.find(params[:user_id])
    @followers = @user.followers.paginate(page: params[:page])
  end

  def following_users
    @user = User.friendly.find(params[:user_id])
    @followings = @user.following.paginate(page: params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def feed
    users = current_user.follower_ids
    users << current_user.following_ids
    users << current_user.id
    users.flatten!.uniq!
    @tweets = Tweet.where(user_id: users).paginate(page: params[:page]).order(created_at: :desc)
  end
end
 

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweet = Tweet.new()
  end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:tweet_id])
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body).merge(user: current_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:user_id])
    @tweets = @user.tweets.paginate(page: params[:page])
  end

  def search_user
  end

  def search
    if params[:username].present?
      @users = User.search(params[:username])
      @users = current_user.except_current_user(@users)
      if @users
        respond_to do |format|
          format.js { render partial: 'users/user_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Could not find a user'
          format.js { render partial: 'users/user_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a username'
        format.js { render partial: 'users/user_result' }
      end
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/follower_users.html.erb
<%= link_to @user.username, user_tweets_path(@user) %>
<h1>Followers</h1>

<div class="row">
  <div class="col-12">
    <div class="col-6 mx-auto">
      <table class="table">
        <% @followers.each do |follower| %>
        <tr>
          <td>
            <%= link_to follower.full_name, user_tweets_path(follower) %>
          </td>
          <td>
            <%= follower.username %><br>
          </td>
          <td>
            <% unless current_user.id == follower.id %>
              <% if current_user.already_followed?(follower.id) %>
                <span class="badge badge-success">Following</span>
              <% else %>
                <%= link_to 'Follow', follow_path(follower.id), method: :post, class: 'btn btn-warning'  %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <% end %>

        <div class="my-4 mx-auto col-6">
          <%= will_paginate @followers %>
        </div>
      </table>
    </div>
  </div>
</div>

app/views/follows/following_users.html.erb
<%= link_to @user.username, user_tweets_path(@user) %>
<h1>Following</h1>

<div class="row">
  <div class="col-12">
    <div class="col-6 mx-auto">
      <table class="table">
        <% @followings.each do |following| %>
        <tr>
          <td>
            <%= link_to following.full_name, user_tweets_path(following) %>
          </td>
          <td>
            <%= following.username %><br>
          </td>
          <td>
            <% unless current_user.id == following.id %>
              <% if current_user.already_followed?(following.id) %>
                <span class="badge badge-success">Following</span>
              <% else %>
                <%= link_to 'Follow', follow_path(following.id), method: :post, class: 'btn btn-warning'  %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <% end %>

        <div class="my-4 mx-auto col-6">
          <%= will_paginate @followings %>
        </div>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="collapse navbar-collapse  mr-3" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item mr-3">
        <%= link_to 'Tweeter clone', root_path, class: 'text-light' %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to 'Tweet', new_tweet_path, class: 'text-light' %>
      </li>
      <li class="nav-item  mr-3">
        <%= link_to 'Search user', search_user_path, class: 'text-light' %>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item mr-3">
        <%= link_to current_user.username, user_tweets_path(current_user), class: 'text-light' %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'text-light' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if  user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% end %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div  class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/feed.html.erb
  <h2>Feed</h2>
  
<div class="row">
  <div class="col-12">
    <div class="my-4 col-6 mx-auto">
      <%= link_to 'Tweet', new_tweet_path, class: 'btn btn-success btn-lg' %>
    </div>

    
    <% @tweets.each do |tweet| %>
    <div class="card my-4 mx-auto col-6 ">
      <div class="card-header">
        <%= tweet.user.full_name %>, @<%= tweet.user.username %> - <%= time_ago_in_words(tweet.created_at) %> ago<br>
      </div>
      <div class="card-body">
        <%= tweet.body %>
      </div>
    </div>
    <% end %>

    <div class="my-4 mx-auto col-6">
      <%= will_paginate @tweets %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1 class="mb-5">New tweet</h1>

<div class="row">
  <div class="col-12">
    <div class="col-6 mx-auto">
      <%= form_with model: @tweet do |f| %>
        <div class="form-group">
          <%= f.label :body %>        
          <%= f.text_area :body, class: 'form-control' %>
          <br>
          <%= f.submit 'tweet', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user_result.html.erb
<% if @users %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><strong>Full name: </strong> <%= user.full_name %></td>
            <td><strong>Username: </strong> <%= user.username %></td>
            <td><strong>Actions: </strong> <%= link_to "View Profile", user_tweets_path(user), class: "btn btn-sm btn-primary" %>
              <% if current_user.already_followed?(user.id) %>
                <span class="badge badge-success">Following</span>
              <% else %>
              <%= link_to 'Follow', follow_path(user), method: :post, class: 'btn btn-warning'  %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_user_result.js.erb
document.querySelector('#user-results').innerHTML = '<%= j render "users/user_result.html" %>'

app/views/users/search_user.html.erb
<div class="search-area">
  <h1>Search user</h1>
  <%= form_tag search_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :username, params[:user], placeholder: 'Username', class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag 'Search', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

<div id="user-results">
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.full_name %>
</h1>
<p>
  <%= @user.username %>

  <% unless current_user.id == @user.id %>
    <% if current_user.already_followed?(@user.id) %>
      <%= link_to 'Unfollow', delete_follow_path(@user), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'Follow', follow_path(@user), method: :post, class: 'btn btn-warning'  %>
    <% end %>
  <% end %>
</p>
<p>
</p>

<table class="table"> 
  <tr>
    <th style="text-align: center;">tweets</th>
    <th style="text-align: center;"><%= link_to 'Followers', follower_users_path(@user) %></th>
    <th style="text-align: center;"><%= link_to 'Following', followings_users_path(@user) %></th>
  </tr>
  <tr>
    <td style="text-align: center;"><%= @user.tweets.size %></td>
    <td style="text-align: center;"><%= @user.followers.size %></td>
    <td style="text-align: center;"><%= @user.following.size %></td>
  </tr>
</table>

<div class="row">
  <div class="col-12">
    <div class="my-4 col-6 mx-auto">
      <%= link_to 'Tweet', new_tweet_path, class: 'btn btn-success btn-lg' if current_user.id == @user.id%>
    </div>

    <% @tweets.each do |tweet| %>
      <div class="card my-4 mx-auto col-6 ">
        <div class="card-header">
          <%= tweet.user.full_name %>, @<%= tweet.user.username %> - <%= time_ago_in_words(tweet.created_at) %> ago<br>
        </div>
        <div class="card-body">
          <%= tweet.body %>
        </div>
      </div>
    <% end %>
    
    <div class="my-4 mx-auto col-6">
      <%= will_paginate @tweets %>
    </div>
  </div>
</div>